### ISSUE TITLE
Please create a release for melpa stable

### ISSUE THREAD

**Issue by Trevoke** [zenspider/enhanced-ruby-mode#100]
All you need to do is tag the commits you consider to be stable as you go and push them to Github and Melpa will take care of the rest.

Thanks!

**Comment by zenspider** [comment]
Is this just a copy/paste spam? Haven't I been doing this for 2 years now?

**Comment by Trevoke** [comment]
I apologize if my request came over as anything but a request. Would you please help me figure out how I could have worded the request better so it would have come across that way?

I believe there is value for the community in so-called stable releases for the packages, beyond the question of reproach on the maintainer's ability to maintain.

**Comment by zenspider** [comment]
It does come across as a request (but so does nigerian spam 😛)... It wasn't a matter of wording, so much as I was confused as to WHY you were sending it to me the request as I already tag this project specifically for melpa.

**Comment by Trevoke** [comment]
enh-ruby-mode does not show up on Melpa stable, so if you have been adding tags, I believe the culprit may be a missing `version-regexp` in melpa's package definition (and/or unparseable tags):

> `:version-regexp` is a regular expression for extracting a version-string from the repository tags. Version-strings must be parseable by Emacs' `version-to-list`, so for an unusual tag like "OTP-18.1.5", we add `:version-regexp "[^0-9]*\\(.*\\)"` to strip the "OTP-" prefix.

**Comment by zenspider** [comment]
I just added melpa/melpa#4160

Please let me know if that is not sufficient. I'm not sure how to test for melpa stable.

**Comment by Trevoke** [comment]
I think that should be sufficient, but frankly, I don't *know* either. I think we wait for Steve to act as benevolent dictator, tell us how to  fix it if we did it wrong, and merge it in. On my package I use "0.5.0" as a tag and it works ( https://stable.melpa.org/#/sqlup-mode )

**Comment by zenspider** [comment]
I've fixed my tags to match the expected format. I suspect that's all that really needs to be done.

**Comment by Trevoke** [comment]
It's fixed, it shows up. I'm sorry what I requested was so unclear. Thank you so much for being responsive and for maintaining this package for the community.
