### ISSUE TITLE
Support Ruby 2.3's &. Safe Navigation Operator

### ISSUE THREAD

**Issue by CyborgMaster** [zenspider/enhanced-ruby-mode#101]
I looks like enh-ruby-mode doesn't correctly parse the `&.` from safe ruby mode.

From the 2.3 release notes

> A safe navigation operator (so-called lonely operator) &., which already exists in C#, Groovy, and Swift, is introduced to ease nil handling as obj&.foo. Array#dig and Hash#dig are also added. Note that this behaves like try! of Active Support, which specially handles only nil.

The following happens when I try to use it in an enh buffer.

![image](https://cloud.githubusercontent.com/assets/1882579/17748496/fafd337a-6476-11e6-9831-5d52b9687f70.png)

**Comment by zenspider** [comment]
Run `C-h v enh-ruby-program RET` and see what ruby you're using. This is mine:

```
enh-ruby-program is a variable defined in `enh-ruby-mode.el'.
Its value is "/Users/ryan/.rbenv/versions/2.3.1/bin/ruby"
Original value was "ruby"
```

**Comment by CyborgMaster** [comment]
Thank you for pointing me in the right direction.  Mine looks like this:  

```
enh-ruby-program is a variable defined in `enh-ruby-mode.el'.
Its value is "ruby"
```

I use RVM and had upgraded the ruby version for my project, but not the default system ruby version.  Once I changed the default, everything parsed as expected.  

Thank you!  And thanks for maintaining an awesome package, I use it all day every day and couldn't live without it.
