### ISSUE TITLE
Parent mode is not prog-mode but enh-ruby-parent-mode

### ISSUE THREAD

**Issue by saidie** [zenspider/enhanced-ruby-mode#102]
I noticed that the parent mode of `enh-ruby-mode` is neither `prog-mode` nor `fundamental-mode` as specified [here](https://github.com/zenspider/enhanced-ruby-mode/blob/c4e8803ffbc14d1a5cd6f7caafae49d36e14ae6f/enh-ruby-mode.el#L234-L238). It seems to be `enh-ruby-parent-mode`:

```elisp
(get 'enh-ruby-mode 'derived-mode-parent)
enh-ruby-parent-mode
```

I encountered a real world problem that a default function of `company-mode`, in which is `company-dabbrev-code`, is not turned on in `enh-ruby-mode` buffer because the function works in modes derived from `prog-mode` by default [like this](https://github.com/company-mode/company-mode/blob/86c1f608b201a2ac544736918a318af7eb4c2d93/company-dabbrev-code.el#L37).

Thanks.

**Comment by zenspider** [comment]
That's an interesting bug. It _Looks Like_ this is done correctly to me.

```
(symbol-function 'enh-ruby-parent-mode) ; => prog-mode
```

But on the other hand:

```
(derived-mode-p 'prog-mode 'enh-ruby-parent-mode) ; => enh-ruby-parent-mode
```

Maybe @purcell can chime in?

**Comment by zenspider** [comment]
That said, I'm also pretty happy to revert that change, seeing as emacs < 24 is > 5 years old at this point.

**Comment by purcell** [comment]
@saidie Is that in a specific Emacs version?

In any case, it'd also be fine to declare a package dependency on `(emacs "24")` and just derive from `prog-mode`.

**Comment by saidie** [comment]
Hi, I tested in several environments with `--no-init-file`:

```elisp
;;; Run before every test
(add-to-list 'load-path "/path/to/enhanced-ruby-mode/repo")
(require 'enh-ruby-mode)

;;; Test 1: Mac OS X (Emacs 24.5.1)
(emacs-version) ; => "GNU Emacs 24.5.1 (x86_64-apple-darwin15.6.0)
                ; =>  of 2016-08-02 on elcapitanvm.local"
(symbol-function 'enh-ruby-parent-mode) ; => prog-mode
(get 'enh-ruby-mode 'derived-mode-parent) ; => enh-ruby-parent-mode
(with-temp-buffer (enh-ruby-mode)
  (derived-mode-p 'prog-mode 'enh-ruby-parent-mode)) ; => enh-ruby-parent-mode

;;; Test 2: Mac OS X (Emacs 25.1.1)
(emacs-version) ; => "GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0)
                ; =>  of 2016-09-18"
(symbol-function 'enh-ruby-parent-mode) ; => prog-mode
(get 'enh-ruby-mode 'derived-mode-parent) ; => enh-ruby-parent-mode
(with-temp-buffer (enh-ruby-mode)
  (derived-mode-p 'prog-mode 'enh-ruby-parent-mode)) ; => enh-ruby-parent-mode

;;; Test 3: Linux (Emacs 25.1.1)
(emacs-version) ; => "GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu)
                ; =>  of 2016-09-20"
(symbol-function 'enh-ruby-parent-mode) ; => prog-mode
(get 'enh-ruby-mode 'derived-mode-parent) ; => enh-ruby-parent-mode
(with-temp-buffer (enh-ruby-mode)
  (derived-mode-p 'prog-mode 'enh-ruby-parent-mode)) ; => enh-ruby-parent-mode
```

In all my tests, `derived-mode-p` returns `enh-ruby-parent-mode`.

> In any case, it'd also be fine to declare a package dependency on (emacs "24") and just derive from prog-mode.

If it is ok, I'm happy :D

**Comment by zenspider** [comment]
Now I'm confused. Now you are suggesting that it is working fine?

**Comment by saidie** [comment]
Sorry for confusing you. My test code is not clear for describing the problem I'm facing. Here is a more good example:

```elisp
;;; not clear
(with-temp-buffer (enh-ruby-mode)
  (derived-mode-p 'prog-mode 'enh-ruby-parent-mode)) ; => enh-ruby-parent-mode

;;; more clear
(with-temp-buffer (enh-ruby-mode)
  (derived-mode-p 'prog-mode)) ; => nil
```

I'm expecting the latter code returns `prog-mode` but it returns `nil` in all of above environments.

**Comment by xiongtx** [comment]
There should be no problem getting rid of `enh-ruby-parent-mode` and deriving from `prog-mode` directly.

A number of packages out there rely on `derived-mode-p`; aliasing `prog-mode` breaks it, which should definitely be fixed.

**Comment by zenspider** [comment]
This is done. Thanks!
