### ISSUE TITLE
MELPA version is quite old

### ISSUE THREAD

**Issue by toothbrush** [zenspider/enhanced-ruby-mode#106]
Maybe the MELPA version of `enh-ruby-mode` should be updated, it is currently from August '16.  I'd be happy to do that sometime, but i'm not sure about the process / haven't had the time to figure out how, yet.

EDIT: i see that that's the date of the last commit to this repo, so i should learn to read better.

**Comment by zenspider** [comment]
That is just because nothing has been pushed since then. There was nothing to release.

I've recently merged a few PRs and pushed a couple commits of my own so it should bump automatically.

**Comment by zenspider** [comment]
Please reopen if this isn't automatically handled my melpa soon.
