### ISSUE TITLE
Squiggly heredoc (<<~) is not properly highlighted

### ISSUE THREAD

**Issue by mrcasals** [zenspider/enhanced-ruby-mode#109]
Ruby syntax highlighting does not correctly highlight HEREDOC symbols. Ruby 2.3.0 introduced the [so-called *squiggly heredoc*](https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc):

```ruby
      description(<<~HEREDOC)
        Finds the schools that the given user can manage. Result
        varies depending on the product the user belongs to and the user role
      HEREDOC
```

The highlighter correctly detects the `<<-HEREDOC` variant, but fails to recognise the `<<~` one:

![](https://i.imgur.com/5aLBuYD.png)
![](https://i.imgur.com/yzYDWhc.png)

I'm using Spacemacs with `enh-ruby-mode` enabled: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/ruby and everything is up to date (both spacemacs and layers).

**Comment by zenspider** [comment]
I can't reproduce this. I wind up with the exact same highlighting for all three of these:

```ruby
f(<<NORMAL)
  Finds the thingy and the other thingy
NORMAL

f(<<-DASHED)
  Finds the thingy and the other thingy
DASHED

f(<<~UGH)
  Finds the thingy and the other thingy
UGH
```

**Comment by zenspider** [comment]
If you can still reproduce this, can you show me what versions and relevant settings you have?

**Comment by zenspider** [comment]
No response. Closing.

**Comment by mrcasals** [comment]
@zenspider Hi! Sorry for the lack of updates... I have since moved on and I don't remember if I ever got to fix this, sorry 😞
