### ISSUE TITLE
Array Literals `%w and %i` are not highlighted.

### ISSUE THREAD

**Issue by h8is2w8** [zenspider/enhanced-ruby-mode#120]
Hello! 

I want my Emacs to highlight arrays as well as it highlights strings with % notation. 

This is how it looks now: 
<img width="241" alt="screen shot 2017-10-13 at 8 53 15 pm" src="https://user-images.githubusercontent.com/5069065/31559228-91e42360-b058-11e7-8338-611002761364.png">

Does it designed behavior? If it is, can I somehow customize `enh-ruby-mode` settings to highlight array literals?

I use Emacs 25.3 for macOS with `enh-ruby-mode` enabled.

Thanks in advance!

**Comment by zenspider** [comment]
Nope. that isn't supported at the moment. If you do `M-x describe-face` while the point is inside the string, you'll see `font-lock-string-face` and if you do the same over the array you'll just see `default`. 

It is probably possible to extend the lexing to include that type of array as a string type for the elements within. Look at erm_buffer.rb.

**Comment by zenspider** [comment]
anything?

**Comment by zenspider** [comment]
Fixed in latest commit.
