### ISSUE TITLE
Is this mode still useful with Ruby 2.4.2 and GNU Emacs 25.3.1?

### ISSUE THREAD

**Issue by anildigital** [zenspider/enhanced-ruby-mode#121]
Is this mode still useful with Ruby 2.4.2 and GNU Emacs 25.3.1? Please mention supporting Ruby and Emacs version if not mentioned. Thanks.

**Comment by zenspider** [comment]
Do you have an actual issue?

**Comment by zenspider** [comment]
Closing this as it feels too much like trolling. If you have an actual issue, please file one. 

How to ask the right questions to get you the right answer: https://www.mikeash.com/getting_answers.html

**Comment by anildigital** [comment]
Ah somewhere docs talked about Ruby 1.9 and +. That seemed so long before. So this question. Sorry, there was no intent to troll.
