### ISSUE TITLE
Error highlighting a ruby buffer

### ISSUE THREAD

**Issue by magandrez** [zenspider/enhanced-ruby-mode#126]
After opening an otherwise normal ruby script (couple of hundred lines, no methods), enh-ruby-mode fails to highlight the source code. Closing the buffer is not possible and I get the following error in *Messages*

```error in process filter: ArgumentError: unknown encoding name: undecided: (ripper):1
/Users/manuel/.emacs.d/.cask/25.3/elpa/enh-ruby-mode-20171101.1638/ruby/erm_buffer.rb:124:in ‘parse’
/Users/manuel/.emacs.d/.cask/25.3/elpa/enh-ruby-mode-20171101.1638/ruby/erm_buffer.rb:124:in ‘block in parse’
/Users/manuel/.emacs.d/.cask/25.3/elpa/enh-ruby-mode-20171101.1638/ruby/erm_buffer.rb:123:in ‘catch’
/Users/manuel/.emacs.d/.cask/25.3/elpa/enh-ruby-mode-20171101.1638/ruby/erm_buffer.rb:123:in ‘parse’
/Users/manuel/.emacs.d/.cask/25.3/elpa/enh-ruby-mode-20171101.1638/ruby/erm_buffer.rb:672:in ‘parse’
/Users/manuel/.emacs.d/.cask/25.3/elpa/enh-ruby-mode-20171101.1638/ruby/erm.rb:45:in ‘<main>’ 
```

Running emacs on Mac OS X (from Homebrew cask): `GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12`

Any idea of what could be causing this?

**Comment by magandrez** [comment]
Note: I confirmed this behaviour (not highlighting properly) affects ruby > 2.4

**Comment by zenspider** [comment]
Not sure, but I've fixed a similar sounding bug recently. Can you check that you still have a problem against the latest version?

Also, are you having a problem with ruby 2.4? Or just prereleases?

**Comment by magandrez** [comment]
Hi,

Ruby 2.4 and above, not with pre-releases.

**Comment by zenspider** [comment]
Does that mean you've verified that you still have the problem with the latest version?

**Comment by zenspider** [comment]
... you need to work with me...

**Comment by zenspider** [comment]
I haven't seen this in a long while so I'm going to assume this is fixed.
