### ISSUE TITLE
Highlighting breaks when using magic variable

### ISSUE THREAD

**Issue by c0imbra** [zenspider/enhanced-ruby-mode#130]
I'm not sure if this is a known behaviour, but the highlighting breaks when using backquote for the magic variable __$`__ or when using quotes inside percent literals.

![highlight-break](https://i.imgur.com/94XMRKQ.gif)

Is there any chance of fixing this?

**Comment by c0imbra** [comment]
Apparently the percent literal issue can be solved by escaping the characters (silly me). But unfortunately the magic variable still breaks the highlighting, and the only workaround is to import the english library instead.

**Comment by stoodfarback** [comment]
Both of these cases highlight correctly for me:
![screenshot-2018-01-16-16 40 08](https://user-images.githubusercontent.com/45657/35019475-f5a088bc-fadb-11e7-966d-081de5f2dc1e.png)

There was a similar issue earlier with quotes inside heredocs (see #119).
Make sure you have the latest version of enh-ruby-mode to see if it's the same problem.

It might also be something else in your configuration. Try a barebones config of emacs, with just enh-ruby-mode, and see if the problem persists.

**Comment by c0imbra** [comment]
@stoodfarback I'm quite sure I have the latest version. I also found out that the highlighting goes normal once I switch to "ruby mode" and "enh-ruby-mode", so it's probably not an issue with the package itself. 
![issue-fixed](https://i.imgur.com/Z6bQFVG.gif)
It's best to close this issue now, as I probably will procrastinate to dig any further into this. Thanks for the help.
