### ISSUE TITLE
Could not find this repo if find enhanced-ruby-mode in github

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#144]
Do you think rename this repo to `enh-ruby-mode` ?

**Comment by muirrn** [comment]
Google search works fine. I think github search is due to this repo being a [fork](https://help.github.com/articles/searching-in-forks/).

**Comment by zenspider** [comment]
I think renaming it would screw up a lot of systems. Sorry. I don't think this is a good idea.

I always search for packages not via google or github search, but via melpa. They always link to the repos.
