### ISSUE TITLE
Poor performance on large files

### ISSUE THREAD

**Issue by muirrn** [zenspider/enhanced-ruby-mode#146]
On very large files (~5k lines), pressing RET to make a new line has a noticeable delay. `enh-ruby-indent-line` calls `erm-wait-for-parse` which does a synchronous full parse. No single thing is particularly slow, but the combination of waiting for erm.rb, parsing the response and calculating the indent adds up to a few hundred milliseconds, which is unbearable slow since you make new lines all the time.

I was considering a couple approaches to speed this up:

1. Don't do full reparse of file. Maybe we could start with just reparsing the current function, or some other way to limit the scope. This would likely speed up various other operations on big files. I imagine it would be a complicated change to make, but I haven't really looked.
2. Don't reparse at all in `enh-ruby-indent-line`. If the only change is inserting a newline, most of the time you don't need to reparse to calculate the indentation. I imagine this is easier than 1), but might not fix other big file performance issues lurking.

Do you have any thoughts?

**Comment by Nondv** [comment]
> Do you have any thoughts?

I am pretty sure it's not healthy to have files with 5k lines of ruby code:)

**Comment by zenspider** [comment]
Define "noticable delay"? 

I have many ruby files with ~5kloc and hitting return in them, even at the bottom of the file, seems fine enough to me. I'm not sure how to programmatically measure this tho. If I figure that out, I'll let you know.

**Comment by zenspider** [comment]
Cool beans:

```
(with-current-buffer "ruby25_parser.rb"
  (goto-char (point-max))
  ;; (electric-indent-mode -1) ; uncomment this and notice a HUGE speedup

  (profiler-start 'cpu)
  (--dotimes 10 (call-interactively 'newline))
  (profiler-report)
  (profiler-stop))
```

This shows:

```
+ ...                                                             316  63%
- command-execute                                                 179  36%
 - call-interactively                                             179  36%
  - funcall-interactively                                         179  36%
   - eval-last-sexp                                               179  36%
    - elisp--eval-last-sexp                                       179  36%
     - eval                                                       179  36%
      - save-current-buffer                                       179  36%
       - let                                                      179  36%
        - while                                                   179  36%
         - call-interactively                                     179  36%
          - funcall-interactively                                 179  36%
           - newline                                              179  36%
            - self-insert-command                                 178  35%
             + electric-indent-post-self-insert-function                169  34%
             + erm-req-parse                                        9   1%
```

So, in my case, nearly all the time (169/179) is being spent on `electric-indent` and almost nothing is spent on `erm-req-parse`. If I disable `electric-indent-mode` the profile is near zero time spent on anything.

Can you run the profiling code and share your results?

**Comment by zenspider** [comment]
No response from OP... poke

**Comment by muirrn** [comment]
> Define "noticable delay"?

It takes around 350ms to insert a newline in my big file:

```
(with-current-buffer "my_big_file.rb"
  (goto-char (point-max))
  (setq start (float-time))
  (call-interactively 'newline)
  (message "%f" (- (float-time) start)))
```

> nearly all the time (169/179) is being spent on electric-indent 

If you keep expanding your profiling output (and it is like mine), electric indent is just calling `enh-ruby-indent-line`, where it spends all its time.

**Comment by muirrn** [comment]
Thanks.
