### ISSUE TITLE
Quoted symbols as hash keys

### ISSUE THREAD

**Issue by andreasknoepfle** [zenspider/enhanced-ruby-mode#150]
Enh-Ruby mode syntax highlighting seems to be broken for symbols that use quotes:

Example: 
```
def some_function('param': nil)
end
```
=>
<img width="307" alt="screen shot 2017-03-24 at 15 34 11" src="https://cloud.githubusercontent.com/assets/239398/24298803/70e1eafe-10a7-11e7-9990-cc2e8898257c.png">

Another example:

<img width="258" alt="screen shot 2017-03-24 at 15 33 36" src="https://cloud.githubusercontent.com/assets/239398/24298816/7ac80e9a-10a7-11e7-861e-43752ef8d514.png">

It messes up syntax highlighting from that point on onwards, where it always looks a bit like it is off by 2 chars or something. You can already see it on the `i` of `nil` that something is off in the example.

**Comment by zenspider** [comment]
Unfortunately, your example isn't valid syntax:

```ruby
# bug.rb
def some_function('param': nil)
end
```

```
bug.rb:1: syntax error, unexpected tSTRING_BEG, expecting ')'
def some_function('param': nil)
                  ^
bug.rb:1: warning: possibly useless use of nil in void context
```

That's tested under ruby 2.x (x=3..6) at least, maybe it was valid in 1.9?

**Comment by zenspider** [comment]
Your other example:

```ruby
class SomeNiceThing
  def some_function
    { 'param=': nil }
    SomeOtherThing::Some.new
  end
end
```

seems to work fine with the current version. Can you update and try to find another example that doesn't work for you?

**Comment by zenspider** [comment]
Closing. Please file a new issue if you can find another example.
