### ISSUE TITLE
Single quote in heredoc breaks 

### ISSUE THREAD

**Issue by valrus** [zenspider/enhanced-ruby-mode#151]
Possibly related to #127  - in the following file

```
class X
  PARSING_HASH = {
    a: {
      b: {
        c: [
          {
            after: 2.days,
            message: <<~MESSAGE
              '
            MESSAGE
          }
        ]
      }
    }
  }
end
```

I get `Scan error: "unbalanced parentheses"` message when trying to use `evil-matchit` to jump between any pairs of braces. If you don't use evil I found that I can also get the same with `forward-sexp`.

Related to #127, I found I could also get this if I replace the single quote with a double quote or backtick.

**Comment by zenspider** [comment]
I don't use `evil`, let alone `evil-matchit`, but `forward-sexp` works fine for me with this example at all levels (inside to out, or across the whole thing).

Can you tell me what version you have and where you got it? Can you reproduce with `emacs -Q` and loading the library?

**Comment by valrus** [comment]
Looks like the version is `enh-ruby-mode-20180730.2309` from ELPA. I'm using [doom-emacs](https://github.com/hlissner/doom-emacs) so it's very possible something's interfering. I'll test in `emacs -Q` when I have a chance.

**Comment by zenspider** [comment]
I tagged today's push of you get yours from melpa-stable.

**Comment by zenspider** [comment]
Anything?

**Comment by valrus** [comment]
Tried the new version - worked fine in `emacs -Q`. Must be something in doom - I'll open an issue there. Thanks!

**Comment by zenspider** [comment]
Please link it here
