### ISSUE TITLE
highlight not working when worked with git-timemachine.el

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#152]
`git-timemachine.el` can make current buffer show history git content in
current buffer, and with a special buffer name, like this: `timemachine:feeds.rb`
(buffer name  a colon is included)

reproduce:

### set enh-ruby-mode as default rb file mode:
```cl
(require 'enh-ruby-mode)
;; (require 'ruby-mode)
(add-to-list 'auto-mode-alist '("\\.\\(rb\\|rake\\|ru\\|gemspec\\|jbuilder\\|rjs\\|xlsx\.axlsx\\)\\'" . enh-ruby-mode))
```

### current buffer is fallback to last commit buffer,  with a name `timemachine:?????.rb`.

Following is a screenshot

![image](https://user-images.githubusercontent.com/549126/48906028-2783e980-ee9e-11e8-88cb-d9289628f3f9.png)

And, git-timemachine worked with other mode and builtin ruby-mode.

Thanks

**Comment by mirubiri** [comment]
Same issue here

**Comment by zenspider** [comment]
OK. This one is odd. The mode is still active, but obviously not doing it's job. `C-h m` shows the key bindings still assigned, but they don't really work (they're doing stuff, but not relevant to the code). Running `M-x erm-reset` brings everything back (testing with `C-m-a`) and keeps git-timemachine active. But no errors go to `*Messages*` or anything. 🤷‍♀️

**Comment by zenspider** [comment]
And I can confirm that haskell-mode and git-timemachine seem to be perfectly happy with each other. How odd.

**Comment by zenspider** [comment]
Filed a bug here: 
https://gitlab.com/pidu/git-timemachine/issues/73

**Comment by pidu** [comment]
I added a workaround calling `erm-reset-buffer`on revision change.

**Comment by zw963** [comment]
> I added a workaround calling `erm-reset-buffer`on revision change.

where？

**Comment by pidu** [comment]
In git-timemachine.

**Comment by zw963** [comment]
@pidu , Cool, it worked now, thank you!
