### ISSUE TITLE
Syntax detect or broken syntax error cause CPU high usage.

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#157]
Basically, i am recent always working on big ruby file. (1000+ lines)

when some error happen, e.g. double quotes not paired, missing ] or ),  etc ...
often cause 100%  CPU usage, it will restore to normal usage after
a while(several seconds), but when keeping editing,  this case happen more 
frequently.

I though this maybe not a bug, but, if we can defer syntax detect(e.g. delay 5 second)
it will be have more better performance i think.

Thanks.

----

More question, i use one stand alone cutted version ruby 2.6 as this mode parser,
`(setq enh-ruby-program "ruby-portable")`, And parse current project ruby-2.3.1 file.

https://github.com/zw963/ruby_tools

Do you think this maybe cause more bad performance than use RVM ruby?

**Comment by zenspider** [comment]
No, I'm experiencing it too, so I don't think it is the ruby you're using. Not sure how to track it down. I've tried `debugger-on-quit` and didn't get anything in my backtraces. I've just backed up to the last tagged version and that seems to be fine... but I haven't determined if it is a cumulative effect thing or immediate.

**Comment by zw963** [comment]
@zenspider , Hi, when i update to newest version, 1f72eb5, current emacs is idle frequently when edit.
i need press many times C-g, to cancel this idle status. after i switch to `ruby-mode`, it worked.

**Comment by zw963** [comment]
more accurate, when i press "Ctrl-x Ctrl+S" to save buffer, emacs is idle.

**Comment by zenspider** [comment]
I rolled out the change that seems to be the culprit. This should be "fixed" for now.

Thank you for the report!
