### ISSUE TITLE
enh-ruby-mode will cause emacs idle frequently when editor.

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#161]
Hi, when i update to newest version, 1f72eb5, current emacs is idle frequently when edit.
Emacs CPU usage is 100%, but no see any ruby process have very high CPU usage.
i need press dozens times C-g, to cancel this idle status. but, when i continue input, it 
happen again, i have to switch to "ruby-mode" to make it work.

after i switch to ruby-mode, it worked.

This situation is happen only on specify buffer(content) which opened by `enh-ruby-mode`, there is a clue, when i enable `ruby-mode`, i found the ruby-mode highlight is not work, current cursor position content always render as "within string".

![image](https://user-images.githubusercontent.com/549126/56633405-8a1d2380-6690-11e9-89a4-5ba84eccfd52.png)

The above image, when I input  ``ge`` in ``get_rate_plan", will result idle. 

I upload [expedia.zip](https://github.com/zenspider/enhanced-ruby-mode/files/3110616/expedia.zip), please goto line 65, after input " ge" after "def", will into idle loop.

Thanks

**Comment by zw963** [comment]
Hi, @zenspider , after revert the last commit: 1f72eb5, the idle issue is gone.

I guess this bug is introduced in this commit.

**Comment by zenspider** [comment]
I've rolled out `forward-sexp-function` for now until I can figure this out.
