### ISSUE TITLE
Local variable and method colorizing 

### ISSUE THREAD

**Issue by ccmywish** [zenspider/enhanced-ruby-mode#173]
I'm customizing a [doom theme](https://github.com/hlissner/emacs-doom-themes/pull/545) and I find neither doom theme can colorize the local variable and method call with enh-ruby-mode.  

Below are the language-specific elements in the doom theme, I find nothing that can be related to Ruby's local variable and method call.

1. builtin        
2. comments       
3. doc-comments 
4. constants     
5. functions     
6. keywords      
7. methods        
8. operators     
9. type           
10. strings        
11. variables      
12. numbers        

You can see the two screenshots(Emacs vs VSCode), the theme in Emacs leaves too much plain white in contrast to VSCode's. And I think it may be the issue of env-hanced-mode rather than doom theme. Can we solve this problem? Any advice is much appreciated.

![emacs](https://user-images.githubusercontent.com/63459097/101331741-5b78ae80-38af-11eb-9dc5-247d5e67227c.png)

![vscode](https://user-images.githubusercontent.com/63459097/101331450-f8871780-38ae-11eb-8a7e-2744193bc3bd.png)

**Comment by zenspider** [comment]
Personally, I don't find this to be a problem, but I've been coding in ruby for 20 years (and have never been a fan of [Angry Fruit Salad](https://www.emacswiki.org/emacs/AngryFruitSalad) no matter what language I'm coding in).

If you want to work on this, go for it. I'm not going to be putting effort into this tho.

**Comment by ccmywish** [comment]
@zenspider Thanks for your reply. I should learn from your spirit and I'll try to work on it.  : )
