### ISSUE TITLE
Conflict with helper.el that is part of Emacs

### ISSUE THREAD

**Issue by tarsius** [zenspider/enhanced-ruby-mode#181]
Please rename `helper.el` a library by the same name is part of Emacs.

I understand that this is just for testing, but consider the following (which does not apply 100%) in this case:

**Comment by tarsius** [comment]
Test files should not `provide` a feature. Providing a feature is only suitable for libraries that are loaded by other libraries/packages or by the end user using `require`. For `require` to be able to do its job, the library that provides the feature has to be located on the `load-path`, but test files should *not* be located on the `load-path`.

You are probably already loading this test file using something like `(load "relative/path/to/it")` and can just remove the `provide` form.  If not, then you probably just have to replace a `require` with a such a `load` form somewhere.

One reason why test files should not `provide` a feature and/or reside on the `load-path` is that authors tend to name those files just `tests.el` or something like that.  If only one package does that, then that works, but it only takes two out of several thousands and things start to get problematic. In fact I usually don't notice such issues until there actually are two packages that provide the exact same "testing feature".

<sub>I have written similar messages many many times so I now [use a template](https://help.github.com/en/github/writing-on-github/working-with-saved-replies). I try to adjust it to match each individual case but it might still not apply 100% in all cases.</sub>

**Comment by zenspider** [comment]
In removing the `require`, my tests no longer byte compile cleanly. All of the ert tests that were clean now look like this:

```
test/enh-ruby-mode-test.el:507:14:Warning: reference to free variable
    ‘enh-ruby-paren-mode-if/close’
```

I haven't seen this one before...

**Comment by tarsius** [comment]
Did you also replace `(require 'helper)` with something like `(load "path/to/helper.el")`?

I don't understand Ruby or Rakefiles, so I don't really understand where the byte-compiling of the tests happen, but I guess you might also have to adjust code around `emacs "--batch -f batch-byte-compile #{t.source}"`.

**Comment by zenspider** [comment]
Figured it out. This should be taken care of. Thanks.

**Comment by tarsius** [comment]
That was confusing! You posted just one second after me. :grinning:

**Comment by tarsius** [comment]
Thanks!
