### ISSUE TITLE
Change syntax of :, @ and $ to "'"

### ISSUE THREAD

**Issue by dgutov** [zenspider/enhanced-ruby-mode#182]
`ruby-mode` has been doing this for a number of years, and it would be great if `enh-ruby-mode` followed suit for consistency and compatibility.

These choices are better for dabbrev completion, for example.

Also: https://github.com/dgutov/robe/issues/132

**Comment by zenspider** [comment]
Mmmm... I'm gonna need more of a clue than that. Help?

**Comment by dgutov** [comment]
This should help:

https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/ruby-mode.el#L180-L183

vs

https://github.com/zenspider/enhanced-ruby-mode/blob/master/enh-ruby-mode.el#L296-L299

**Comment by zenspider** [comment]
Gotcha... I had honed in on that area in ERM but wasn't sure.

**Comment by dgutov** [comment]
To be clear, this issue is only about three characters: `:`, `@` and `$`.

**Comment by zenspider** [comment]
Tacking this on and taking it for a spin:

```elisp
;; https://github.com/zenspider/enhanced-ruby-mode/issues/182
(setq enh-ruby-mode-syntax-table
 (let ((table enh-ruby-mode-syntax-table))
   (modify-syntax-entry ?$  "'"  table)
   (modify-syntax-entry ?:  "'"  table)
   (modify-syntax-entry ?@  "'"  table)

   table))
```
