### ISSUE TITLE
make insert "{ " configurable for ruby-do-end-to-brace.

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#183]
Yes, what i means is this line.

https://github.com/zenspider/enhanced-ruby-mode/blob/master/enh-ruby-mode.el#L712

I have to override this function with my own version in my own config.

the only changes is `insert "{"` instead of `insert "{ "`. (remove ending space when use my own version)

that is:

```rb
[1,2,3].each do |x|
  |
end
```

will change to 

```rb
[1,2,3].each {|x|
  |
}
```

instead of 

```rb
[1,2,3].each { |x|
  |
}
```

Thank you.

**Comment by zw963** [comment]
i guess this comment come from original emacs ruby-mode, but anyway, i don't know where to create issue for `ruby-mode`.

**Comment by zenspider** [comment]
You're filing tickets on this project for problems with ruby-mode??? Seriously my dude... No.
