### ISSUE TITLE
Add a options for ruby-toggle-block as done in ruby-mode.

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#185]
Please check discuss here. 

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53321

thank you.

**Comment by zenspider** [comment]
patches welcome

**Comment by zenspider** [comment]
No. Please refrain from filing issues like this. If you want to contribute to the project, then please do so... but don't give me homework.
