### ISSUE TITLE
"value omission in Hash literals" syntax from Ruby 3.1

### ISSUE THREAD

**Issue by nfedyashev** [zenspider/enhanced-ruby-mode#191]
I'm not sure if that's something in my Emacs configuration or that [value omission in Hash literals](https://github.com/ruby/ruby/commit/c60dbcd1c55cd77a24c41d5e1a9555622be8b2b8) is not supported in enh-ruby-mode:

![enh-ruby-mode](https://user-images.githubusercontent.com/61983/177637978-a4bf872b-edcf-49f3-ab42-cf3ee9ac6774.png)

As a workaround, I had to disable syntax checks(via `enh-ruby-check-syntax`).

Is there a better solution to this?
Thanks

**Comment by stoodfarback** [comment]
Works correctly for me.
One possibility: if you have multiple versions of ruby installed, it might be picking up an older version (which doesn't support the new syntax).
You can specify which binary should be used like so:
`(setq enh-ruby-program "(path-to-latest-ruby)/bin/ruby")`

**Comment by zenspider** [comment]
I just added the following command to help diagnose these issues:

65167d91ae7c65433de81a406a1eaca075ff5ff1

**Comment by nfedyashev** [comment]
I think I can reliably reproduce it

1. Open project A(.ruby-version file is 2.5.0). Open any ruby file.
2. Switch to another project B using projectile (.ruby-version is 3.1.2)
3. "value omission in Hash literals" is treated as invalid syntax.

But If I start my Email(spacemacs) and open Project B(using projectile) right away, then there aren't any issues with Ruby 3.1 syntax highlighting, no warnings.

@zenspider after switching from project A to project B:

```
erm-ruby-program -v = 3.1.2p20
```

Messages tab after switching to Project B look a bit like this:
```
[yas] Prepared just-in-time loading of snippets successfully. [2 times]
[rbenv] using 2.5.0
[rbenv] Using ruby version from .ruby-version file.


LSP :: Connected to [ruby-ls:160970/starting].
[rbenv] using 3.1.2
[rbenv] Using ruby version from .ruby-version file.
```

HTH

//cc @stoodfarback

**Comment by zenspider** [comment]
ERM doesn't use `.ruby-version` but it will use your PATH if you don't have `enh-ruby-program` set and are firing emacs up in each project I guess...

So, don't do that? Set `enh-ruby-program` to your 3.1 version and you will be fine.

**Comment by nfedyashev** [comment]
`describe-variable enh-ruby-program`

> It's value is `/home/username/.rbenv/shims/ruby` 
> Original value was "ruby"

I'm using spacemacs, if that's important to mention:

```
(defun dotspacemacs-configuration-layers ()
   '((ruby :variables 
           ruby-enable-enh-ruby-mode t
           ruby-version-manager 'rbenv)))
```

**Comment by zenspider** [comment]
Again, parsing ruby code with the wrong version of ruby isn't gonna work, so don't do that.

Setting `enh-ruby-program` to 3.1 (or whatever) will be more resilient. If you insist on keeping it pointing at a shim, then you're gonna need to use `erm-reset` periodically to restart the parsing process.

**Comment by nfedyashev** [comment]
@zenspider got it. Thank you!
