### ISSUE TITLE
erm-define-faces throws error

### ISSUE THREAD

**Issue by darth-cheney** [zenspider/enhanced-ruby-mode#192]
I am getting lots of face definition errors, and it seems to stem from `erm-define-faces` not calling correctly when the mode first activates. I'm getting the following trace:
```emacs-lisp
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr color-rgb-to-hsl> 0)
  color-rgb-to-hsl()
  color-lighten-name(unspecified -20)
  color-darken-name(unspecified 20)
  erm-darken-color(font-lock-string-face)
  erm-define-faces()
  eval-expression((erm-define-faces) nil nil 127)
  funcall-interactively(eval-expression (erm-define-faces) nil nil 127)
  command-execute(eval-expression)
```

**Comment by zenspider** [comment]
not enough information to go on here... what version of emacs?

But also... somehow you're going from `(erm-darken-color 'font-lock-string-face)` to `(color-darken-name unspecified 20)` ... so, something is going wonky with`font-lock-string-face` on your side? 

can you do `(describe-face '(font-lock-string-face))`

and `(face-attribute 'font-lock-string-face :foreground)` ?

**Comment by zenspider** [comment]
No response. Closing.
