### ISSUE TITLE
Use tree-sitter for indent/hightlight?

### ISSUE THREAD

**Issue by gondalez** [zenspider/enhanced-ruby-mode#193]
Thank you for your work on this mode 🙏 

A bit pie in the sky, but I was curious if there are any plans (or if it even makes sense) to use tree-sitter for highlighting and/or indentation?

I really love the indentation of `enh-ruby-mode`.
I tried using tree-sitter with regular `ruby-mode` and enjoyed the improved highlighting provided by tree-sitter, but the indentation is still pretty basic.

**Comment by aaronjensen** [comment]
@gondalez dgutov is actively working on improving the indentation of `ruby-mode`. Some fixes have already landed in 29 and there are some major changes going into 30 to make it much closer to `enh-ruby-mode`.

**Comment by gondalez** [comment]
That is great news, I look forward to trying it out :) 
Thank you @aaronjensen @dgutov 🙏

**Comment by dgutov** [comment]
> to make it much closer to enh-ruby-mode

More specifically, to add such user option.

Core tree-sitter modes, by the way, will have their own indentaiton logic. We'll also see if we can get `ruby-ts-mode` in Emacs 29 as well (there is an effort ongoing, but I haven't checked on its progress yet).

**Comment by gondalez** [comment]
Closing this since it seems like it will come out in the wash with emacs 29 and `ruby-ts-mode` 🙏
