### ISSUE TITLE
Modify hanging indent

### ISSUE THREAD

**Issue by jpablobr** [zenspider/enhanced-ruby-mode#36]
I would have thought that setting

``` lisp
(setq enh-ruby-hanging-indent-level 0)
```

would let me have the following indentation:

```
ret = if true
  42
end

instead of

ret = if true
        42
      end
```

That's what the `ruby_hanging_indent` in vim does. Is there a way to do this with enh-ruby-mode?

**Comment by patbl** [comment]
`(setq enh-ruby-deep-indent-construct nil)` will now give you the desired behavior: https://github.com/zenspider/enhanced-ruby-mode/pull/110
