### ISSUE TITLE
Allow outdenting access modifiers

### ISSUE THREAD

**Issue by scottjacobsen** [zenspider/enhanced-ruby-mode#58]
I would like to outdent access modifiers. Is there a way to do it, or could an option be added?

I would like to format like this:

``` ruby
class MyClass
  def foo; end
private
  def bar; end
end
```

I haven't figured it out yet. I tried this based on some advice I got [here](https://stackoverflow.com/questions/23818628/outdent-ruby-access-modifiers-in-emacs/23825702?noredirect=1#23825702):

``` lisp
(defadvice enh-ruby-calculate-indent (around outdent-modifiers activate)
  "Outdent access modifiers."
  (if (save-excursion
        (beginning-of-line)
        (looking-at "\s*\\(private\\|protected\\|public\\)\s*$"))
      (setq ad-return-value 0)
    ad-do-it))
```

That does outdent the access modifier, but it also outdents everything that comes after:

``` ruby
class MyClass
  def foo; end
private
def bar; end # :( Want this indented 2 spaces.
end
```

**Comment by zenspider** [comment]
What's the status of this?

**Comment by scottjacobsen** [comment]
Personally I'm off the project that used that weird indenting style and
don't anticipate ever needing it again. I never really got my hack for
this production ready.

**Comment by zenspider** [comment]
kk. Since nobody else is asking for it, I'm gonna close. We can reopen later if it comes up again. Thanks
