### ISSUE TITLE
error in process filter: erm-parse

### ISSUE THREAD

**Issue by agoodno** [zenspider/enhanced-ruby-mode#69]
Sometimes I see this error when applying a stash with magit.

error in process filter: erm-parse: undefined method `add_content' for nil:NilClass: /Users/agoodnough/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm.rb:41:in`<main>'
error in process filter: undefined method `add_content' for nil:NilClass: /Users/agoodnough/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm.rb:41:in`<main>'

It seems to be related to an open file that is being replaced with the version in the stash. Also, it seems to happen on large files. The result is that file is not parsed correctly so the syntax highlighting doesn't get applied. Changing any character triggers the re-parse in that file so it's not a big deal, but thought I'd let you know about it. Thanks.

**Comment by zenspider** [comment]
I know about it. I just can't reproduce it reliably. Any help in that regard is welcome.

**Comment by zenspider** [comment]
I think this is handled or beyond stale. Closing.
