### ISSUE TITLE
Incompatibility with Ruby 2.2.0

### ISSUE THREAD

**Issue by wasamasa** [zenspider/enhanced-ruby-mode#72]
See also #71 for more context.

```
error in process filter: erm-parse: undefined method `size' for nil:NilClass: /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:261:in `on_eol'
/home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:400:in `on_nl'
/home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:121:in `parse'
/home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:121:in `block in parse'
/home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:120:in `catch'
/home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:120:in `parse'
/home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:605:in `parse'
/home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm.rb:44:in `<main>'
```

I get this error when using this mode with Ruby 2.2.0.  Downgrading to Ruby 2.1.5 makes it go away, looks like an incompatible change.  The backtrace suggests it's calling `on_nl nil` somewhere and therefore crashes because that should never happen.

**Comment by zenspider** [comment]
> On Feb 13, 2015, at 13:25, Vasilij Schneidermann <notifications@github.com> wrote:
> 
> See also #71 for more context.
> 
> error in process filter: erm-parse: undefined method `size' for nil:NilClass: /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:261:in `on_eol'
> /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:400:in `on_nl'
> /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:121:in `parse'
> /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:121:in `block in parse'
> /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:120:in `catch'
> /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:120:in `parse'
> /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm_buffer.rb:605:in `parse'
> /home/wasa/.emacs.d/elpa/enh-ruby-mode-20140901.2122/ruby/erm.rb:44:in `<main>'
> 
> I get this error when using this mode with Ruby 2.2.0. Downgrading to Ruby 2.1.5 makes it go away, looks like an incompatible change. The backtrace suggests it's calling on_nl nil somewhere and therefore crashes because that should never happen.

Using 2.2.0 with a fresh emacs? or upgrading / switching ruby versions in the same emacs session? Try experimenting with `erm-reset`.

**Comment by wasamasa** [comment]
Yes, this happens in a fresh Emacs instance. No, `erm-reset` does nothing except giving me the error again (presumably because it's not a problem with the Emacs instance).

**Comment by zenspider** [comment]
OK. Cool. It is probably unrelated to the other problem then. Can you provide a snippet to repro with?

**Comment by wasamasa** [comment]
I think I've narrowed it down to a minimal example:

```rb
'a'.gsub('a', 'b')
  .gsub('b', 'c') # inline comment
  .gsub('c', 'a')
```

Using Ruby 2.1 I get no errors. Using Ruby 2.2 I get the earlier backtrace.

**Comment by vzvu3k6k** [comment]
Nice work :smile: 

Here are [outputs of Ripper.lex(src) on your example in Ruby 2.1.4 and 2.2.0](https://gist.github.com/vzvu3k6k/4ca68e147f38017cbcb3).

An output of [Ripper.lex(src)](http://ruby-doc.org/stdlib-2.2.0/libdoc/ripper/rdoc/Ripper.html#method-c-lex) consists of `[[lineno(), column()], :on_#{event}, tok]` of each token. This is `diff 2.1.4.output 2.2.0.output`.

```diff
16,17c16,19
<  [[1, 18], :on_period, "\n"],
<  [[2, 0], :on_ident, "  .gsub"],
---
>  [[1, 18], :on_ignored_nl, "\n"],
>  [[2, 0], :on_sp, "  "],
>  [[2, 2], :on_period, "."],
>  [[2, 3], :on_ident, "gsub"],
30c32,34
<  [[3, 0], :on_period, "  ."],
---
>  [[1, 18], :on_ignored_nl, nil],
>  [[3, 0], :on_sp, "  "],
>  [[3, 2], :on_period, "."],
```

In Ruby 2.2.0, `on_ignored_nl` (which is an alias of `on_nl` in [erm_buffer.rb](https://github.com/zenspider/enhanced-ruby-mode/blob/cfc08845922065b5674fbc0cfb9e683e5ce75a1f/ruby/erm_buffer.rb#L519)) is invoked twice at the end of the first line, and the token is `nil` in the second call. It is probably the reason of the crash.

---

This is a quick workaround for it.

```diff
diff --git a/ruby/erm_buffer.rb b/ruby/erm_buffer.rb
index b4456b4..8bbbf43 100644
--- a/ruby/erm_buffer.rb
+++ b/ruby/erm_buffer.rb
@@ -299,6 +299,12 @@ class ErmBuffer
       end
     end
 
+    def on_ignored_nl tok
+      unless tok.nil?
+        on_nl tok
+      end
+    end
+
     def on_kw sym # TODO: break up. 61 lines long
       sym = sym.to_sym
       case @mode
@@ -516,7 +522,6 @@ class ErmBuffer
       end
     end
 
-    alias on_ignored_nl on_nl
     alias on_lbracket   on_lparen
     alias on_rbracket   on_rparen
   end
```

**Comment by zenspider** [comment]
Awesome. I've applied your patch @vzvu3k6k. Thanks!

**Comment by gabriel-dehan** [comment]
Hello, there. Still having the issue : 

```
error in process filter: undefined method `size' for nil:NilClass: /home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm_buffer.rb:261:in `on_eol'                                                        
/home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm_buffer.rb:400:in `on_nl'                                                                                                                            
/home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm_buffer.rb:121:in `parse'                                                                                                                            
/home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm_buffer.rb:121:in `block in parse'                                                                                                                   
/home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm_buffer.rb:120:in `catch'                                                                                                                            
/home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm_buffer.rb:120:in `parse'                                                                                                                            
/home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm_buffer.rb:605:in `parse'                                                                                                                            
/home/gaby/.emacs.d/elpa/enh-ruby-mode-20140901.1222/ruby/erm.rb:44:in `<main>'         
```

Around this code :

```ruby
 most_recent_trip = self.trip.class # Trip                                                                                                                                                                   
      .where.not(id: self.trip.id)                                                                                                                                                                                
      .where({ user_id: self.trip.user_id }.merge(hotel_query))                                                                                                                                                   
      .order(created_at: :desc)                                                                                                                                                                                   
      .limit(1)                                                                                                                                                                                                   
      .first          
```     

Seems to be the same problem, any idea why ?

**Comment by wasamasa** [comment]
@gabriel-dehan Your version of `enh-ruby-mode` seems to be too old to contain the above patch.  Please update and try again.

**Comment by zenspider** [comment]
@gabriel-dehan that code works for me under ruby 2.2.2:

```
(set-variable (quote enh-ruby-program) "~/\.rbenv/versions/2\.2\.2/bin/ruby" nil)
(erm-reset)
```

seems to reparse fine

**Comment by gabriel-dehan** [comment]
@wasmasa :+1: , thank you
