### ISSUE TITLE
Allow disabling of automatic encoding comment insertion

### ISSUE THREAD

**Issue by exterm** [zenspider/enhanced-ruby-mode#73]
I want all ruby files interpreted as utf-8 and not comments inserted. As I see it, that's not (easily) possible now. I do not know emacs lisp so have no idea how to fix this...

**Comment by zenspider** [comment]
AFAIK, the encoding comment is inserted automatically by emacs on save. It has little-to-nothing to do with ERM. Poke around in the reference manual in the International section and see what you can find: `C-h r m International RET`

**Comment by exterm** [comment]
For `ruby-mode` I used `(setq ruby-insert-encoding-magic-comment nil)` and it worked. Does not seem to work for `enhanced-ruby-mode` though.

It seems the comment is inserted somewhere around here https://github.com/zenspider/enhanced-ruby-mode/blob/master/enh-ruby-mode.el#L357

**Comment by esiegel** [comment]
There is a [before-save-hook](https://github.com/zenspider/enhanced-ruby-mode/blob/master/enh-ruby-mode.el#L265) which adds the encoding.

I'm fairly new to emacs myself, so I imagine there to be a better way, but since I wasn't able to find any configuration that disallows this hook, I've added some logic in my config that removes this hook when enh loads.

```emacs-lisp
  ;; define our own super awesome hook that will remove the before-save-hook
  (defun remove-enh-magic-comment ()
    (remove-hook 'before-save-hook 'enh-ruby-mode-set-encoding t))

  ;; add the hook to call our super awesome function.
  (add-hook 'enh-ruby-mode-hook 'remove-enh-magic-comment)

  ;; this is for ruby mode
  (setq ruby-insert-encoding-magic-comment nil)
```

**Comment by zenspider** [comment]
There's `enh-ruby-add-encoding-comment-on-save`. Is that sufficient?

**Comment by exterm** [comment]
I can't try it out as I am not using emacs for ruby anymore, but it sounds like it is doing the right thing.

**Comment by zenspider** [comment]
@esiegel ... I assume this is working fine for you, yes?

**Comment by esiegel** [comment]
Yep, still working for me.

**Comment by zenspider** [comment]
Closing.
