### ISSUE TITLE
Getting "rbenv: version 2.2.1 is not installed" error although ruby -v returns 2.2.2

### ISSUE THREAD

**Issue by x-ji** [zenspider/enhanced-ruby-mode#77]
When I first installed `enh-ruby-mode` I was using `2.2.1` with `rbenv` and it worked fine. However after I upgraded to `2.2.2` and uninstalled `2.2.1`, it seems to not recognize the correct Ruby interpreter now. I've set rbenv global, rbenv local to 2.2.2 and exported the environment variable RBENV_VERSION as 2.2.2 in both .zshrc and .bashrc. However "rbenv: version `2.2.1` is not installed". Maybe I can see where does `enh-ruby-mode` pick up ruby version and try to look into it?

**Comment by x-ji** [comment]
Now I manually set `enh-ruby-program "/usr/local/var/rbenv/versions/2.2.2/bin/ruby"`, however the following error is returned:

```
error in process filter: erm-parse: unknown encoding name: class: (ripper):1
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `block in parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `catch'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:610:in `parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm.rb:44:in `<main>'
error in process filter: unknown encoding name: class: (ripper):1
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `block in parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `catch'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:610:in `parse'
/Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm.rb:44:in `<main>'
```

**Comment by zenspider** [comment]
> On Apr 26, 2015, at 22:44, Xiang Ji <notifications@github.com> wrote:
> 
> Now I manually set enh-ruby-program "/usr/local/var/rbenv/versions/2.2.2/bin/ruby", however the following error is returned:
> 
> error in process filter: erm-parse: unknown encoding name: class: (ripper):1
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `block in parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `catch'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:610:in `parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm.rb:44:in `<main>'
> error in process filter: unknown encoding name: class: (ripper):1
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:121:in `block in parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `catch'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:120:in `parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm_buffer.rb:610:in `parse'
> /Users/JX/.emacs.d/elpa/enh-ruby-mode-20150312.1458/ruby/erm.rb:44:in `<main>'

Did you make sure to run `erm-reset` after changing the path?

**Comment by x-ji** [comment]
Umm... Running that seems to give me the same errors.

**Comment by x-ji** [comment]
Not sure what happened. For now I'm reinstalling `2.2.1` in `rbenv` to make Enhanced Ruby Mode function correctly. Hopefully it will impact my projects using `2.2.2`

**Comment by zenspider** [comment]
I don't seem to have any problems when hardcoding my `enh-ruby-program` to `2.2.2`. Closing.
