### ISSUE TITLE
A "stand-alone" hash not being indented correctly

### ISSUE THREAD

**Issue by art-solopov** [zenspider/enhanced-ruby-mode#78]
![enh-ruby-indent-error](https://cloud.githubusercontent.com/assets/5079987/7514203/177d111a-f4c4-11e4-9503-29a4448b3e28.png)
Please note that if I:
- Remove the `a, b = do_something` line
- Write an assignment statement (i.e., `h = {...}`)
  The issue disappears, the indentation applied correctly.
  I've encountered this error first in my Rspec `let` statement, if anyone wonders how realistic my example is.

_P. S._ If I just leave the hash stand-alone, the error persists.
![enh-ruby-indent-error-2](https://cloud.githubusercontent.com/assets/5079987/7514286/c44b78d2-f4c4-11e4-9646-f8dc5e614864.png)

**Comment by zenspider** [comment]
Please don't submit _graphics_ in the stead of actual source. I can't do anything with graphics.

**Comment by zenspider** [comment]
The hash, standalone, works fine:

```ruby
{
 a: a,
 b: b
}
```

If you make it look like a block, it seems to misindent:

```ruby
x {
  a: a,
    b: b
}
```

but since that isn't valid ruby, I'm not sure I care about that scenario.

Oddly, the original scenario has the same problem (and I suspect they're related):

```ruby
a, b = do_something
{
  a: a,
    b: b
}
```

**Comment by zenspider** [comment]
(Ugly) Workaround: put a semicolon after `do_something`.

**Comment by art-solopov** [comment]
It looks like the mode doesn't account for line feeds when distinguishing between hashes and blocks.

**Comment by muirrn** [comment]
This issue is resolved now right?

**Comment by zenspider** [comment]
yup yup. thanks!
