### ISSUE TITLE
Incorrect multi-line Hash indentation

### ISSUE THREAD

**Issue by Eilie** [zenspider/enhanced-ruby-mode#80]
Currently indentation works like this:
```ruby
foo = {
       x: 1
      }
```
But should work like this:
```ruby
foo = {
  x: 1
}
```

This also applies to arrays. Original `ruby-mode` works as expected.

**Comment by stoodfarback** [comment]
Yep, there's an option for that, `enh-ruby-deep-indent-paren`. If you don't know how to edit options for emacs, adding this to the end of your .emacs should work in most cases:

    (setq enh-ruby-deep-indent-paren nil)

**Comment by Eilie** [comment]
@stoodfarback It works, thank you!
