### ISSUE TITLE
"def" doesn't trigger automatic "end"

### ISSUE THREAD

**Issue by Eilie** [zenspider/enhanced-ruby-mode#81]
Either `class` `SPC` or `module` `SPC` will add closing `end` automatically but for some reason it doesn't work with `def` `SPC`.

**Comment by zenspider** [comment]
Are you sure that's enhanced-ruby-mode? I see that it has `enh-ruby-electric-brace`.

**Comment by Eilie** [comment]
@zenspider Not 100% sure, do you think EnhRuby doesn't responsible for this?

**Comment by zenspider** [comment]
I have no idea. I don't use such functionality. Since you say `SPC` is the trigger, Do `C-h k SPC` while in a ruby file and see what function is bound to the key.

**Comment by Eilie** [comment]
@zenspider It says `SPC` is bound to `self-insert-command`.

**Comment by zenspider** [comment]
That just means it only adds a space. I can't help if I can't reproduce. You're going to have to figure out what mode or feature is doing this on your system if I'm going to be able to assist.

**Comment by Eilie** [comment]
@zenspider Figured that out, smartparens is responsible for this feature, and it was broken by evil-escape.
