### ISSUE TITLE
enh-ruby-end-of-defun moving to end of file

### ISSUE THREAD

**Issue by shreyasns** [zenspider/enhanced-ruby-mode#84]
After updating my package enh-ruby-end-of-defun is moving to end of file instead of the end of function.

**Comment by zenspider** [comment]
Can you please provide input and steps to reproduce?

**Comment by shreyasns** [comment]
class test
  def abc
    ##lorem ipsum
    ##asdad
  end

  def ddef
    #asda
    #fssf
  end
end

when I hit C-M-e it takes me to end of class instead of end of function that I'm currently in. And I also noticed that it works correctly when I open the file with -q.
