### ISSUE TITLE
Continuation indent

### ISSUE THREAD

**Issue by Kukunin** [zenspider/enhanced-ruby-mode#87]
Hello. Sorry in advance, I'm new to the emacs and elisp. 

I'm faced with some indentation problem, primarily in my rspec files. For instance, I have a line: 

```ruby 
expect(response_json[:error]).to include(type: 'InvalidCredentials', message: 'The email/password pair is not valid')
```

and when I try to push `type` key to new line, it indents wrong for me. Actually, it indents as:

```ruby
expect(response_json[:error]).to include(
                                         type: 'InvalidCredentials', message: 'The email/password pair is not valid')
```

while I want:

```ruby
expect(response_json[:error]).to include(
  type: 'InvalidCredentials', message: 'The email/password pair is not valid')
```

Even if I have multiline hash argument, `enh-ruby-mode` indents it as:

```ruby
expect(response_json[:error]).to include(
                                         type: 'InvalidCredentials',
                                         message: 'The email/password pair is not valid'
                                        )

```

while I want: 

```ruby
expect(response_json[:error]).to include(
  type: 'InvalidCredentials',
  message: 'The email/password pair is not valid'
)
```

**Comment by stoodfarback** [comment]
Yep, there's an option for that, `enh-ruby-deep-indent-paren`. If you don't know how to edit options for emacs, adding this to the end of your .emacs should work in most cases:

    (setq enh-ruby-deep-indent-paren nil)

**Comment by Kukunin** [comment]
it works like a charm. Thanks!
