### ISSUE TITLE
wrong indent after `protected :x=`

### ISSUE THREAD

**Issue by stardiviner** [zenspider/enhanced-ruby-mode#88]
here is the test code:

``` ruby
class A
  attr_accessor :x
  protected :x=
            def initialize(x=1)
              @x = x
            end
end
```

As you can see. the indent is wrong after `protected :x=`.

**Comment by zenspider** [comment]
Sorry for the delay...

I can't reproduce this... so either I don't have the same settings as you do or it's been fixed.

Can you re-try your sample above?

**Comment by stardiviner** [comment]
I figured it out, it is caused by option:
```elisp
(setq enh-ruby-use-ruby-mode-show-parens-config t)
```
