### ISSUE TITLE
Deep indent parent only for paren-wrapped statements

### ISSUE THREAD

**Issue by alexgirdler** [zenspider/enhanced-ruby-mode#90]
I'm not sure if this is a configuration error on my part or if `enh-ruby-mode-deep-indent-paren` doesn't do what I expected it to do.

This is how I want the code to look:

``` ruby
RailsModel.create(:some_attr => 'a_value',
                  :secret    => 42, 
                  :works     => true)

literal_array = [
  :contains,
  :some,
  :keys
]
```

If I enable `enh-ruby-mode-deep-indent-paren` this is what I get:

``` ruby
RailsModel.create(:some_attr => 'a_value',
                  :secret    => 42,
                  :works     => true)

literal_array = [
         :contains,
         :some,
         :keys
        ]
```

If I disable that then I get this:

``` ruby
RailsModel.create(:some_attr => 'a_value',
  :secret    => 42,
  :works     => true)

literal_array = [
  :contains,
  :some,
  :keys
]
```

Is there something I am doing wrong? Or is there a way to get my desired indentation from this?

**Comment by alexgirdler** [comment]
This also goes for any literal syntax. Is there a way to make literal syntax not use the deep-indent-paren setting?

**Comment by zenspider** [comment]
This is what I see with my normal settings (which iirc are pretty much the defaults--yup, just double-checked):

```ruby
RailsModel.create(:some_attr => 'a_value',
                  :secret    => 42,
                  :works     => true)

literal_array = [
                 :contains,
                 :some,
                 :keys
                ]
```

I plopped that into a file, selected everything, and forced a reindent with plain `indent-region`.

Can you look through your customize list (or .emacs.el if you setq things) and show me your settings wrt enh-ruby-mode?

Looking at the settings, `enh-ruby-deep-paren` is `t` by default. Turning it off and reindenting I get:

```ruby
RailsModel.create(:some_attr => 'a_value',
  :secret    => 42,
  :works     => true)

literal_array = [
  :contains,
  :some,
  :keys
]
```

which matches your second example.

Can you also ensure you're not using a mix of tabs and spaces or something odd?

**Comment by zenspider** [comment]
Just checked with `emacs -q`. In ruby-mode:

```ruby
RailsModel.create(:some_attr => 'a_value',
                  :secret    => 42,
                  :works     => true)

literal_array = [
  :contains,
  :some,
  :keys
]
```

and in enh-ruby-mode:

```ruby
RailsModel.create(:some_attr => 'a_value',
                  :secret    => 42,
                  :works     => true)

literal_array = [
                 :contains,
                 :some,
                 :keys
                ]
```

So, I think this is working correctly out of the box and there is some other variable messing with things. I'd like to figure this out. We might have to bisect your emacs.el or something.

**Comment by alexgirdler** [comment]
My bad I messed up the formatting of the example of what I get when I enable `enh-ruby-deep-indent-paren` I get what you posted for enh-ruby-mode. However I want it to appear like it does in normal ruby mode. I also don't have any settings enabled.

**Comment by zenspider** [comment]
so you want a hybrid between the first and the second depending on method call vs literal...

**Comment by alexgirdler** [comment]
Yes, it's what ruby-mode does by default

**Comment by dgutov** [comment]
> depending on method call vs literal...

Depending, rather, on whether the opening paren/brace/bracket is followed by an element, or the newline comes first. That's what ruby-mode does, at least.

**Comment by zenspider** [comment]
I'm unassigning this. It works for the way I code. If someone wants to take a whack at a PR I'm happy to merge.

**Comment by zenspider** [comment]
OK... I just added some tests that are very similar to this problem... can someone take a whack at writing tests for this problem?

**Comment by dgutov** [comment]
Lots of indentation examples here: http://git.savannah.gnu.org/cgit/emacs.git/tree/test/manual/indent/ruby.rb
