### ISSUE TITLE
add face for string interpolate in string

### ISSUE THREAD

**Issue by stardiviner** [zenspider/enhanced-ruby-mode#95]
I think add a face for string interpolate in string will help programmer to looks easily on string.
What do you think?

**Comment by zenspider** [comment]
Not sure I understand. Here is a contrived example of what it currently does:

![screen shot 2016-03-15 at 20 02 28](https://cloud.githubusercontent.com/assets/9832/13800703/e115c1f0-eae8-11e5-8507-fc5b52166aa8.png)

**Comment by stardiviner** [comment]
Sorry, It did, my example does not highlight might because they are not highlighted originally in `enh-ruby-mode`.
