### ISSUE TITLE
Breaks ruby-add-log-current-method

### ISSUE THREAD

**Issue by dgutov** [zenspider/enhanced-ruby-mode#96]
Take this example, move point to `bar`:

``` ruby
class Test
  def foo
    bar
  end
end
```

`(ruby-add-log-current-method)` should return `"Test#foo"`. It returns `"Test"` instead.

I'd be happy if `(enh-ruby-add-log-current-method)` returned the expected value, but that doesn't happen either.

Originally reported as https://github.com/dgutov/robe/issues/47#issuecomment-217531509.

**Comment by zenspider** [comment]
Can you point me at some doco or something for this? Esp a contract of some sort.

What calls this function and why? I wouldn't expect a `ruby-*` function to work in ERM.

**Comment by dgutov** [comment]
`add-log-current-defun` does. `robe-context` does too.

> I wouldn't expect a ruby-* function to work in ERM.

What about `enh-ruby-add-log-current-method`, then?

**Comment by dgutov** [comment]
> Can you point me at some doco or something for this?

`ruby-add-log-current-method` has a docstring with examples.

**Comment by zenspider** [comment]
I _think_ I just fixed this for most forms.

**Comment by dgutov** [comment]
The lack of support for `class << self` is unfortunate: we do use this form, for instance. Another problem is that it does not return fully qualified module names. Example:

```rb
module A
  module B
    class C
      def foo
        _
      end
    end
  end
end
```

`(enh-ruby-add-log-current-method)` returns `"C#foo"` instead of `"A::B::C#foo"`.

**Comment by zenspider** [comment]
Failing tests would be more actionable...

**Comment by dgutov** [comment]
Isn't the above description unambiguous? I hope you realize I'm not using this major mode myself.

**Comment by dgutov** [comment]
But check these out: https://github.com/emacs-mirror/emacs/blob/b6a57fb80c49bcd9163966d612671a5256f3a1a8/test/lisp/progmodes/ruby-mode-tests.el#L492-L559

**Comment by zenspider** [comment]
Closing in favor of #156.
