### ISSUE TITLE
Support for new syntax for hash keys like "foo": 

### ISSUE THREAD

**Issue by yxhuvud** [zenspider/enhanced-ruby-mode#97]
Nowadays ruby supports symbolic hash keys like "foo-bar":. This break the parsing of the ruby files for me. 

Example: 

```
# This works
foo(:"foo-key1" => bar, 
  :"foo-key2" => bar2
)

# This doesn't
foo("foo-key1": bar, 
  "foo-key2": bar2
)
```

Also, it would be nice to have a documented way to forcibly restart a broken parser instance. erm-reset does not help in this case.

**Comment by zenspider** [comment]
This is probably fixed. Please test and close if resolved.

**Comment by yxhuvud** [comment]
Yup, seems to work. Great!
