### ISSUE TITLE
Render failed when (setq vc-follow-symlinks t) and then open a symlinked rb file.

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#99]
### 1. start emacs with only following config;

``` cl
(setq vc-follow-symlinks t)
(require 'enh-ruby-mode)
(setq enh-ruby-program "my/1.9/ruby/pah")
(add-to-list 'interpreter-mode-alist '("ruby" . enh-ruby-mode))
```
### get error:

``` cl
error in process filter: save-current-buffer: Selecting deleted buffer
error in process filter: Selecting deleted buffer
```

Thanks.

**Comment by zw963** [comment]
Hi, @zenspider ,  Does I describe not clear enough?

I just want to know if I explain what i want. and the issue is could reproduce ?

thanks

**Comment by zw963** [comment]
More explain:

I have a file, it location is:  `/home/zw963/Dropbox/linux/utils/capistrano/tasks/assets.rake`
But, I have another symlink, which is: `/home/zw963/utils/capistrano/tasks/assets.rake`

If I open this file with `emacsclient -nc  /home/zw963/utils/capistrano/tasks/assets.rake`, I can see a emacs `*Messages*` log with:
`Followed link to /home/zw963/Dropbox/linux/utils/capistrano/tasks/assets.rake`

In this case, this file could not correct rendered by this mode.

we can see following error:
```el
error in process filter: save-current-buffer: Selecting deleted buffer
error in process filter: Selecting deleted buffer
```

This bug is still exist.

Thanks.

**Comment by zw963** [comment]
More seriously is:

It caused all `*.rake` file could not be load correct even I access a this file from it original path.
I have to restart my emacs daemon to make it worked.

**Comment by zenspider** [comment]
I think this is fixed by cleaning up process management. The "Selecting deleted buffer" errors seem to have been excised.

**Comment by zw963** [comment]
This worked now, Thank very much!
